services:
  db:
    image: postgres:15
    container_name: sdap-postgres
    environment:
      POSTGRES_USER: sdap_user
      POSTGRES_PASSWORD: sdap_password
      POSTGRES_DB: sdap_db
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
